services:
  - type: web
    name: mixpost
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: mixpost-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: mixpost-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: mixpost-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: mixpost-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: mixpost-db
          property: password

databases:
  - name: mixpost-db
    plan: free 